title_category_map = {
    "Flat for sale": "Flat",
    "Prodej bytu": "Flat",
    "Predaj bytu": "Flat",
    "Flat to rent": "Flat",
    "Pronájem bytu": "Flat",
    "Prenájom bytu": "Flat",
    "Studio": "Studio",
    "Garsoniéra": "Studio",
    "Small studio": "Small",
    "1+kk": "Small",
    "1 bedroom": "1",
    "1+1": "1",
    "2+kk": "2+kk",
    "2 bedroom": "2",
    "2+1": "2",
    "3+kk": "3+kk",
    "3+1": "3+1",
    "4+kk": "4+kk",
    "4+1": "4+1",
    "5+kk": "5",
    "5+1": "5+1",
    "6+kk": "6+kk",
    "6+1": "6+1",
    "7+kk": "7+kk",
    "7+1": "7+1",
    "House for sale": "House",
    "Prodej domu": "House",
    "Predaj domu": "House",
    "House to rent": "House",
    "Pronájem domu": "House",
    "Prenájom domu": "House",
    "5 bedroom": "5",
    "Plot to rent": "Plot",
    "Pronájem pozemku": "Plot",
    "Prenájom pozemku": "Plot",
    "Plot for sale": "Plot",
    "Prodej pozemku": "Plot",
    "Predaj pozemku": "Plot",
    "Garage for sale": "Garage",
    "Prodej garáže": "Garage",
    "Predaj garáže": "Garage",
    "Garage to rent": "Garage",
    "Pronájem garáže": "Garage",
    "Prenájom garáže": "Garage",
    "Office to rent": "Office",
    "Pronájem kanceláře": "Office",
    "Prenájom kancelárie": "Office",
    "Office for sale": "Office",
    "Prodej kanceláře": "Office",
    "Predaj kancelárie": "Office",
    "Commercial property for sale": "Commercial",
    "Prodej nebytového prostoru": "Commercial",
    "Predaj nebytového priestoru": "Commercial",
    "Commercial property to rent": "Commercial",
    "Pronájem nebytového prostoru": "Commercial",
    "Prenájom nebytového priestoru": "Commercial",
    "Recreational property to rent": "Recreational",
    "Pronájem chaty, chalupy": "Recreational",
    "Prenájom rekreačného objektu": "Recreational",
    "Recreational property for sale": "Recreational",
    "Prodej chaty, chalupy": "Recreational",
    "Predaj rekreačného objektu": "Recreational",
}
